In [1]:
import numpy as np
import pandas as pd
import plotly.express as px

In [2]:
pd.set_option('display.max_rows', None)

In [3]:

import pandas as pd
pd.reset_option('^display.')

In [4]:
df = pd.read_csv(r'D:\CDSP\Sessions\Project\student_exam_performance_analysis\student_exam_performance.csv')

In [5]:
df.drop('student_id', axis=1, inplace=True)
df

,age,gender,education_level,school_type,family_income,parent_education,urban_rural,previous_exam_score,previous_gpa,attendance_percentage,...,exam_difficulty,exam_preparation_days,questions_attempted,questions_correct,time_management_score,exam_anxiety_level,exam_score,performance_grade,pass_status,performance_level
0,20,Female,High School,Public,Middle,NaN,Rural,78.36,2.95,81.49,...,Medium,27,95,86,NaN,9.39,90.40,A,Pass,High
1,17,Male,High School,Public,Middle,NaN,Suburban,73.40,2.89,NaN,...,Easy,4,100,86,87.17,6.31,86.21,A,Pass,High
2,18,Other,Undergraduate,Public,Middle,Master,Urban,82.76,3.35,100.00,...,Easy,28,96,74,63.77,9.87,76.11,B,Pass,Medium
3,20,Male,High School,Public,Middle,High School,Suburban,60.61,2.57,84.91,...,Medium,16,97,77,59.51,9.68,79.74,B,Pass,Medium
4,16,Female,High School,Private,High,Bachelor,Suburban,74.79,2.84,88.21,...,Medium,28,98,52,84.64,10.00,50.66,D,Pass,Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,17,Male,Undergraduate,Public,Upper-Middle,NaN,Suburban,78.73,NaN,89.67,...,Medium,5,95,62,76.13,8.36,66.46,C,Pass,Medium
99996,14,Female,High School,Public,Upper-Middle,Bachelor,Suburban,75.70,2.98,83.87,...,Easy,24,94,91,84.29,8.68,96.54,A,Pass,High
99997,16,Female,High School,Public,Upper-Middle,High School,Suburban,84.69,3.27,89.57,...,Medium,24,85,65,62.32,9.97,74.66,C,Pass,Medium
99998,15,Female,High School,Private,High,Master,Rural,74.70,3.06,92.61,...,Medium,28,93,81,100.00,10.00,85.85,A,Pass,High
99999,18,Female,Undergraduate,Charter,Lower-Middle,NaN,Urban,76.73,2.97,90.32,...,Medium,1,92,52,NaN,10.00,54.40,D,Pass,Low

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 43 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   age                         100000 non-null  int64
 1   gender                      100000 non-null  str
 2   education_level             100000 non-null  str
 3   school_type                 100000 non-null  str
 4   family_income               100000 non-null  str
 5   parent_education            93474 non-null   str
 6   urban_rural                 100000 non-null  str
 7   previous_exam_score         100000 non-null  float64
 8   previous_gpa                92207 non-null   float64
 9   attendance_percentage       90137 non-null   float64
 10  assignment_completion_rate  100000 non-null  float64
 11  class_participation         100000 non-null  str
 12  study_hours_per_day         100000 non-null  float64
 13  self_study_hours            100000 non-null  float64
 14  private_tuition             100000 non-null  int64
 15  online_learning_hours       100000 non-null  float64
 16  study_consistency           100000 non-null  str
 17  study_environment           100000 non-null  str
 18  study_method                100000 non-null  str
 19  revision_frequency          100000 non-null  str
 20  practice_tests_completed    100000 non-null  int64
 21  notes_quality               91593 non-null   str
 22  sleep_hours                 100000 non-null  float64
 23  sleep_quality               93006 non-null   str
 24  daily_screen_time           100000 non-null  float64
 25  physical_activity_hours     100000 non-null  float64
 26  break_frequency             100000 non-null  str
 27  stress_level                100000 non-null  int64
 28  motivation_level            100000 non-null  str
 29  internet_access             100000 non-null  int64
 30  device_availability         97035 non-null   str
 31  educational_app_usage       100000 non-null  str
 32  online_course_hours         100000 non-null  float64
 33  exam_difficulty             100000 non-null  str
 34  exam_preparation_days       100000 non-null  int64
 35  questions_attempted         100000 non-null  int64
 36  questions_correct           100000 non-null  int64
 37  time_management_score       90387 non-null   float64
 38  exam_anxiety_level          100000 non-null  float64
 39  exam_score                  100000 non-null  float64
 40  performance_grade           100000 non-null  str
 41  pass_status                 100000 non-null  str
 42  performance_level           100000 non-null  str
dtypes: float64(14), int64(8), str(21)
memory usage: 32.8 MB

In [7]:
df['private_tuition'] = df['private_tuition'].astype('str')

def change_private_tuition(x):
    if x == '0':
        x = 'No'
    elif x == '1':
        x = 'Yes'
    return x


df['private_tuition'] = df['private_tuition'].apply(change_private_tuition)

In [8]:
df['internet_access'] = df['internet_access'].astype('str')


def change_internet_access(x):
    if '0' in x:
        x = 'No'
    elif '1' in x:
        x = 'Yes'
    else:
        print('error')

    return x

df['internet_access'] = df['internet_access'].apply(change_internet_access)

df['internet_access']

0        Yes
1        Yes
2        Yes
3        Yes
4        Yes
        ...
99995    Yes
99996    Yes
99997    Yes
99998    Yes
99999    Yes
Name: internet_access, Length: 100000, dtype: str

In [9]:
df.isna().mean() * 100

age                           0.000
gender                        0.000
education_level               0.000
school_type                   0.000
family_income                 0.000
parent_education              6.526
urban_rural                   0.000
previous_exam_score           0.000
previous_gpa                  7.793
attendance_percentage         9.863
assignment_completion_rate    0.000
class_participation           0.000
study_hours_per_day           0.000
self_study_hours              0.000
private_tuition               0.000
online_learning_hours         0.000
study_consistency             0.000
study_environment             0.000
study_method                  0.000
revision_frequency            0.000
practice_tests_completed      0.000
notes_quality                 8.407
sleep_hours                   0.000
sleep_quality                 6.994
daily_screen_time             0.000
physical_activity_hours       0.000
break_frequency               0.000
stress_level                  0.000
motivation_level              0.000
internet_access               0.000
device_availability           2.965
educational_app_usage         0.000
online_course_hours           0.000
exam_difficulty               0.000
exam_preparation_days         0.000
questions_attempted           0.000
questions_correct             0.000
time_management_score         9.613
exam_anxiety_level            0.000
exam_score                    0.000
performance_grade             0.000
pass_status                   0.000
performance_level             0.000
dtype: float64

In [10]:
df['parent_education'] = df['parent_education'].fillna('Unknown')
df['parent_education'].value_counts(normalize= True) * 100

parent_education
High School    28.122
Bachelor       27.943
Associate      18.640
Master         14.043
Unknown         6.526
Doctorate       4.726
Name: proportion, dtype: float64

In [11]:
df['time_management_score'] = df['time_management_score'].fillna(df['time_management_score'].mean())

In [12]:
df['attendance_percentage'] = df['attendance_percentage'].fillna(df['attendance_percentage'].median())

mask = df.isna().mean() * 100 != 0

nan_cols = (df.isna().mean() * 100)[mask].index.to_list()


for col in nan_cols:
        df[col] = df[col].fillna('Unknown')

In [13]:
df[nan_cols]

      previous_gpa notes_quality sleep_quality device_availability
0             2.95       Average     Excellent              Shared
1             2.89       Average     Excellent              Shared
2             3.35     Excellent          Poor           Dedicated
3             2.57     Excellent          Fair           Dedicated
4             2.84          Poor     Excellent           Dedicated
...            ...           ...           ...                 ...
99995      Unknown       Average          Fair              Shared
99996         2.98       Unknown     Excellent           Dedicated
99997         3.27       Average          Fair           Dedicated
99998         3.06       Average          Poor              Shared
99999         2.97       Average          Good           Dedicated

[100000 rows x 4 columns]

In [14]:
df.isna().mean() * 100

age                           0.0
gender                        0.0
education_level               0.0
school_type                   0.0
family_income                 0.0
parent_education              0.0
urban_rural                   0.0
previous_exam_score           0.0
previous_gpa                  0.0
attendance_percentage         0.0
assignment_completion_rate    0.0
class_participation           0.0
study_hours_per_day           0.0
self_study_hours              0.0
private_tuition               0.0
online_learning_hours         0.0
study_consistency             0.0
study_environment             0.0
study_method                  0.0
revision_frequency            0.0
practice_tests_completed      0.0
notes_quality                 0.0
sleep_hours                   0.0
sleep_quality                 0.0
daily_screen_time             0.0
physical_activity_hours       0.0
break_frequency               0.0
stress_level                  0.0
motivation_level              0.0
internet_access               0.0
device_availability           0.0
educational_app_usage         0.0
online_course_hours           0.0
exam_difficulty               0.0
exam_preparation_days         0.0
questions_attempted           0.0
questions_correct             0.0
time_management_score         0.0
exam_anxiety_level            0.0
exam_score                    0.0
performance_grade             0.0
pass_status                   0.0
performance_level             0.0
dtype: float64

In [15]:
df.duplicated().sum()

np.int64(0)

In [16]:
df.describe(include='int')

,age,practice_tests_completed,stress_level,exam_preparation_days,questions_attempted,questions_correct
count,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000
mean,17.005740,5.509170,9.375640,15.501440,92.492150,57.298240
std,1.999562,2.501131,1.081613,8.644356,4.609376,15.028787
min,14.000000,0.000000,5.000000,1.000000,85.000000,0.000000
25%,15.000000,4.000000,9.000000,8.000000,88.000000,47.000000
50%,17.000000,5.000000,10.000000,16.000000,92.000000,57.000000
75%,19.000000,7.000000,10.000000,23.000000,96.000000,67.000000
max,20.000000,20.000000,10.000000,30.000000,100.000000,100.000000

In [17]:
# Handling outliers

from datasist.structdata import detect_outliers

num_cols = df.select_dtypes(include= 'int').columns.to_list()

mean = df['stress_level'].mean()
outlier_indices = detect_outliers(df, 0, ['stress_level'])
df.loc[outlier_indices,'stress_level'] = mean.round()
for col in num_cols:
    outlier_indices = detect_outliers(df, 0, [col])
    print(col)
    print(outlier_indices)
    print('-'*50)
    median = df[col].median()
    df.loc[outlier_indices,col] = median

df['stress_level']

age
[]
--------------------------------------------------
practice_tests_completed
[25, 94, 121, 138, 156, 177, 216, 223, 247, 254, 278, 283, 346, 385, 414, 421, 530, 608, 687, 697, 730, 907, 987, 1123, 1153, 1228, 1412, 1453, 1472, 1504, 1579, 1655, 1725, 1801, 1871, 1887, 1954, 1961, 1981, 2004, 2046, 2105, 2154, 2160, 2174, 2185, 2193, 2224, 2265, 2301, 2416, 2473, 2550, 2574, 2575, 2603, 2622, 2667, 2794, 2799, 2915, 2933, 2946, 2969, 3022, 3039, 3055, 3093, 3106, 3108, 3299, 3341, 3411, 3450, 3562, 3608, 3626, 3684, 3690, 3795, 3811, 3940, 3994, 3995, 4087, 4090, 4112, 4262, 4292, 4331, 4401, 4425, 4492, 4540, 4544, 4559, 4914, 4968, 5072, 5137, 5189, 5219, 5223, 5241, 5275, 5293, 5310, 5333, 5382, 5488, 5493, 5511, 5662, 5671, 5689, 5825, 5845, 5857, 5952, 6047, 6125, 6157, 6272, 6382, 6543, 6558, 6597, 6626, 6674, 6843, 6887, 6967, 7091, 7270, 7272, 7327, 7332, 7448, 7568, 7661, 7668, 7727, 7829, 7915, 7960, 7998, 8002, 8006, 8096, 8109, 8168, 8234, 8250, 8530, 8539, 8572, 8589, 8619, 8684, 8713, 8841, 8921, 8929, 8943, 8973, 8988, 9002, 9027, 9036, 9158, 9172, 9191, 9207, 9216, 9236, 9254, 9255, 9257, 9259, 9361, 9385, 9449, 9510, 9569, 9761, 9770, 9776, 9808, 9826, 9939, 9980, 9982, 10020, 10030, 10138, 10331, 10378, 10454, 10472, 10564, 10575, 10601, 10603, 10615, 10619, 10634, 10655, 10743, 10769, 10908, 11000, 11044, 11102, 11193, 11260, 11274, 11303, 11306, 11348, 11475, 11480, 11608, 11650, 11651, 11674, 11677, 11701, 11825, 11879, 12024, 12104, 12143, 12200, 12202, 12232, 12424, 12453, 12463, 12464, 12516, 12560, 12583, 12725, 12806, 12819, 12837, 12963, 13066, 13100, 13315, 13526, 13550, 13638, 13669, 13694, 13751, 13789, 13924, 13977, 14001, 14008, 14013, 14031, 14081, 14103, 14205, 14320, 14326, 14336, 14368, 14435, 14465, 14559, 14560, 14583, 14649, 14714, 14755, 14841, 14887, 14921, 14982, 15055, 15066, 15133, 15155, 15171, 15191, 15218, 15223, 15317, 15360, 15385, 15473, 15477, 15735, 15759, 15782, 15980, 16027, 16036, 16220, 16270, 16304, 16511, 16548, 16823, 16842, 16850, 16929, 17021, 17035, 17121, 17301, 17346, 17389, 17448, 17546, 17551, 17585, 17601, 17621, 17773, 17849, 17940, 17993, 18040, 18059, 18191, 18390, 18434, 18588, 18645, 18723, 18724, 18735, 18736, 18765, 18771, 18825, 18880, 18892, 18916, 18957, 18966, 19058, 19114, 19249, 19267, 19269, 19281, 19313, 19352, 19403, 19541, 19548, 19580, 19675, 19733, 19736, 19875, 20016, 20059, 20141, 20144, 20178, 20181, 20200, 20205, 20239, 20261, 20287, 20303, 20411, 20424, 20454, 20510, 20547, 20589, 20626, 20769, 20809, 20869, 20882, 20954, 20981, 21012, 21071, 21112, 21123, 21243, 21263, 21369, 21417, 21420, 21487, 21607, 21630, 21690, 21729, 21757, 21785, 21918, 22022, 22053, 22137, 22174, 22179, 22239, 22252, 22306, 22346, 22362, 22417, 22562, 22721, 22843, 22917, 22967, 23046, 23121, 23194, 23202, 23300, 23380, 23424, 23432, 23457, 23474, 23537, 23559, 23577, 23598, 23641, 23758, 23788, 23875, 23996, 24052, 24079, 24185, 24195, 24204, 24257, 24391, 24412, 24529, 24571, 24697, 24757, 24822, 24828, 24841, 24903, 24905, 24975, 25032, 25091, 25123, 25177, 25422, 25488, 25555, 25607, 25625, 25657, 25796, 25813, 25902, 26024, 26029, 26056, 26138, 26170, 26447, 26472, 26482, 26562, 26674, 26809, 26946, 26970, 27014, 27068, 27227, 27262, 27293, 27298, 27393, 27491, 27549, 27552, 27763, 27777, 27820, 27868, 27918, 27979, 28035, 28167, 28184, 28259, 28361, 28403, 28413, 28428, 28493, 28545, 28566, 28701, 28714, 28728, 28757, 29042, 29061, 29131, 29209, 29260, 29298, 29327, 29346, 29441, 29452, 29463, 29498, 29534, 29536, 29554, 29667, 29716, 29870, 29907, 29914, 29920, 29986, 30015, 30017, 30033, 30098, 30107, 30203, 30280, 30287, 30341, 30444, 30473, 30524, 30554, 30657, 30740, 30749, 30805, 30818, 30825, 30936, 30990, 31031, 31073, 31175, 31212, 31235, 31247, 31250, 31259, 31298, 31310, 31311, 31364, 31365, 31385, 31434, 31473, 31527, 31694, 31751, 31753, 31784, 31901, 31910, 31974, 32007, 32022, 32048, 32126, 32209, 32306, 32727, 32818, 32957, 32981, 33012, 33015, 33037, 33128, 33295, 33399, 33467, 33527, 33585, 33605, 33622, 33635, 33657, 33683, 33782, 33805, 33811, 33878, 33924, 33993, 34306, 34362, 34433, 34511, 34625, 34667, 34679, 34875, 34933, 34967, 35028, 35088, 35117, 35125, 35134, 35169, 35306, 35459, 35470, 35528, 35556, 35712, 35819, 35844, 35886, 35919, 35929, 35998, 36071, 36300, 36302, 36545, 36623, 36627, 36648, 36692, 36782, 36836, 36871, 37124, 37156, 37167, 37192, 37194, 37218, 37308, 37359, 37367, 37536, 37814, 37819, 37838, 37882, 37966, 38040, 38109, 38195, 38203, 38466, 38494, 38542, 38591, 38592, 38621, 38707, 38753, 38813, 38817, 38823, 38847, 38968, 38975, 39039, 39099, 39108, 39150, 39227, 39294, 39598, 39737, 39901, 39993, 40011, 40061, 40078, 40089, 40181, 40204, 40349, 40523, 40540, 40549, 40578, 40601, 40609, 40643, 40667, 40683, 40719, 40792, 41017, 41086, 41191, 41236, 41288, 41299, 41358, 41408, 41525, 41538, 41585, 41615, 41620, 41631, 41648, 41696, 41768, 41883, 41953, 42000, 42066, 42077, 42154, 42155, 42189, 42516, 42604, 42615, 42652, 42715, 42728, 42775, 42777, 42837, 42892, 42893, 42909, 42952, 43070, 43294, 43418, 43558, 43608, 43676, 43699, 43819, 43831, 43849, 43854, 43855, 43857, 43990, 44205, 44238, 44301, 44364, 44459, 44497, 44499, 44500, 44560, 44599, 44633, 44656, 44667, 44716, 44857, 44873, 44895, 45088, 45150, 45161, 45342, 45406, 45412, 45532, 45560, 45619, 45688, 45782, 45930, 45947, 45957, 46034, 46084, 46118, 46313, 46332, 46397, 46412, 46436, 46437, 46470, 46478, 46495, 46499, 46501, 46502, 46504, 46584, 46935, 46962, 47202, 47216, 47336, 47448, 47500, 47505, 47527, 47656, 47798, 47822, 47878, 47893, 47896, 47919, 47959, 48034, 48057, 48075, 48076, 48080, 48192, 48321, 48403, 48413, 48470, 48497, 48513, 48541, 48558, 48610, 48639, 48657, 48667, 48739, 48766, 48778, 48782, 48880, 48967, 49023, 49029, 49097, 49219, 49269, 49346, 49407, 49436, 49481, 49551, 49649, 49744, 49779, 49802, 49978, 50111, 50149, 50198, 50292, 50307, 50322, 50329, 50337, 50405, 50432, 50474, 50570, 50577, 50601, 50745, 50761, 50788, 50866, 50918, 50948, 51070, 51152, 51158, 51201, 51202, 51235, 51263, 51366, 51436, 51438, 51562, 51567, 51637, 51663, 51690, 51694, 51754, 51870, 51872, 52068, 52090, 52177, 52306, 52389, 52409, 52442, 52456, 52542, 52621, 52734, 52764, 52794, 52798, 52863, 52883, 52913, 52953, 52966, 53072, 53163, 53196, 53216, 53261, 53344, 53352, 53375, 53401, 53568, 53667, 53737, 53800, 53853, 53867, 53963, 54024, 54149, 54170, 54280, 54309, 54331, 54393, 54409, 54449, 54564, 54587, 54649, 54671, 54675, 54676, 54770, 54844, 54869, 54920, 55095, 55105, 55221, 55226, 55319, 55456, 55594, 55612, 55665, 55826, 55880, 55932, 56047, 56074, 56124, 56164, 56166, 56192, 56201, 56240, 56331, 56371, 56405, 56437, 56438, 56488, 56496, 56650, 56717, 56744, 56822, 56938, 56949, 56958, 56967, 56968, 56998, 57096, 57188, 57336, 57343, 57403, 57463, 57482, 57536, 57578, 57607, 57630, 57734, 57744, 57747, 57828, 57881, 57894, 57934, 57980, 58149, 58174, 58289, 58318, 58327, 58362, 58429, 58490, 58573, 58614, 58646, 58766, 58907, 58943, 58961, 58983, 59006, 59176, 59196, 59226, 59250, 59270, 59331, 59349, 59441, 59498, 59673, 59682, 59787, 59823, 59829, 59838, 59935, 60199, 60299, 60344, 60347, 60395, 60489, 60496, 60526, 60723, 60809, 60979, 61007, 61019, 61174, 61201, 61426, 61437, 61565, 61581, 61622, 61778, 61805, 61812, 61843, 61846, 62025, 62051, 62124, 62184, 62221, 62296, 62345, 62392, 62424, 62426, 62472, 62482, 62500, 62651, 62652, 62742, 62770, 62818, 62836, 62868, 62871, 62920, 62969, 62972, 63048, 63206, 63224, 63252, 63284, 63331, 63421, 63459, 63558, 63644, 63732, 63750, 63784, 63790, 63797, 63823, 63828, 63898, 63973, 64040, 64132, 64215, 64230, 64283, 64338, 64372, 64468, 64484, 64594, 64702, 64758, 64980, 64986, 65029, 65102, 65137, 65174, 65290, 65325, 65488, 65610, 65836, 65868, 65871, 65873, 65940, 66076, 66094, 66170, 66176, 66281, 66315, 66444, 66486, 66656, 66669, 66700, 66776, 66807, 66836, 67029, 67133, 67177, 67278, 67358, 67381, 67412, 67421, 67486, 67567, 67574, 67604, 67687, 67775, 67795, 67861, 67943, 68181, 68297, 68443, 68559, 68615, 68666, 68711, 68743, 68777, 68829, 68841, 69077, 69088, 69177, 69313, 69392, 69433, 69587, 69602, 69683, 69790, 69810, 69821, 69917, 70009, 70097, 70119, 70141, 70158, 70166, 70204, 70308, 70372, 70380, 70402, 70429, 70519, 70533, 70579, 70690, 70795, 70888, 70910, 70990, 71039, 71101, 71214, 71245, 71265, 71279, 71379, 71450, 71481, 71613, 71630, 71705, 71722, 71785, 71797, 71845, 71899, 71919, 72074, 72094, 72111, 72139, 72192, 72387, 72459, 72521, 72528, 72573, 72574, 72638, 72686, 72828, 73030, 73050, 73094, 73099, 73241, 73291, 73433, 73517, 73669, 73728, 73742, 73747, 73808, 73931, 74121, 74165, 74296, 74301, 74326, 74350, 74362, 74386, 74389, 74430, 74613, 74655, 74741, 74747, 74762, 74789, 74801, 74816, 74937, 74952, 75013, 75124, 75150, 75217, 75278, 75416, 75440, 75560, 75615, 75671, 75680, 75696, 75755, 75797, 75879, 76022, 76060, 76065, 76071, 76095, 76103, 76127, 76156, 76191, 76216, 76284, 76306, 76432, 76463, 76521, 76558, 76634, 76640, 76669, 76793, 76796, 76803, 76845, 76871, 76888, 77017, 77041, 77043, 77167, 77217, 77243, 77315, 77392, 77419, 77454, 77530, 77540, 77569, 77595, 77613, 77654, 77735, 77826, 77837, 77906, 77909, 77938, 78049, 78068, 78215, 78238, 78276, 78288, 78401, 78548, 78654, 78664, 78739, 78742, 78754, 78797, 78820, 78831, 78845, 78884, 78901, 78921, 78963, 79063, 79258, 79284, 79312, 79341, 79359, 79403, 79450, 79476, 79642, 79696, 79759, 79764, 79917, 79937, 80015, 80016, 80055, 80080, 80120, 80159, 80253, 80264, 80395, 80537, 80547, 80669, 80678, 80718, 80719, 80844, 80876, 81064, 81152, 81153, 81245, 81320, 81323, 81399, 81404, 81454, 81464, 81466, 81537, 81543, 81659, 81708, 81764, 81816, 81824, 81825, 81972, 82095, 82195, 82230, 82252, 82760, 82811, 82846, 82858, 82944, 83016, 83030, 83040, 83099, 83171, 83281, 83443, 83466, 83480, 83611, 83644, 83661, 83711, 83948, 83965, 84022, 84028, 84112, 84193, 84400, 84476, 84479, 84560, 84574, 84599, 84653, 84664, 84791, 84837, 85021, 85066, 85071, 85080, 85101, 85143, 85151, 85190, 85219, 85267, 85288, 85436, 85578, 85605, 85715, 85717, 85732, 85738, 85796, 85808, 85812, 85876, 85885, 85953, 85955, 86143, 86148, 86293, 86304, 86343, 86395, 86435, 86467, 86536, 86604, 86624, 86651, 86719, 86750, 86897, 86940, 87141, 87166, 87194, 87209, 87235, 87301, 87327, 87471, 87577, 87631, 87657, 87708, 87727, 87866, 87915, 87931, 87981, 88006, 88032, 88037, 88221, 88273, 88301, 88344, 88372, 88384, 88400, 88435, 88558, 88562, 88598, 88625, 88711, 88745, 88746, 88751, 88818, 88833, 88862, 88877, 88935, 89099, 89105, 89132, 89138, 89300, 89331, 89332, 89445, 89451, 89482, 89501, 89529, 89607, 89704, 89708, 89736, 89814, 89872, 89970, 90038, 90047, 90128, 90142, 90145, 90152, 90203, 90204, 90386, 90510, 90547, 90554, 90555, 90570, 90611, 90721, 90796, 90849, 90898, 90920, 90940, 91060, 91065, 91179, 91212, 91305, 91333, 91344, 91481, 91506, 91542, 91554, 91662, 91730, 91896, 91897, 91945, 92059, 92110, 92203, 92206, 92248, 92264, 92518, 92535, 92697, 92745, 92776, 92995, 92997, 93027, 93041, 93146, 93171, 93229, 93336, 93445, 93564, 93599, 93605, 93633, 93652, 93840, 93945, 93948, 94025, 94052, 94087, 94163, 94201, 94227, 94277, 94295, 94325, 94383, 94497, 94539, 94600, 94616, 94722, 94725, 94868, 94943, 94962, 95084, 95162, 95214, 95268, 95337, 95341, 95382, 95494, 95498, 95616, 95696, 95825, 95963, 96056, 96062, 96077, 96095, 96154, 96199, 96378, 96470, 96685, 96706, 96714, 96775, 96799, 96852, 96925, 96968, 97007, 97123, 97211, 97368, 97470, 97480, 97588, 97594, 97613, 97636, 97717, 97737, 97766, 97791, 97833, 97897, 97907, 97963, 98072, 98090, 98175, 98186, 98249, 98301, 98332, 98376, 98383, 98400, 98483, 98575, 98756, 98783, 98808, 98957, 98974, 99021, 99058, 99236, 99330, 99336, 99419, 99580, 99591, 99741, 99742, 99834, 99902, 99962, 99967, 99978, 99981, 99992, 99996]
--------------------------------------------------
stress_level
[]
--------------------------------------------------
exam_preparation_days
[]
--------------------------------------------------
questions_attempted
[]
--------------------------------------------------
questions_correct
[78, 184, 194, 262, 308, 500, 880, 923, 1152, 1633, 1720, 1740, 1742, 1781, 1804, 2071, 2199, 2357, 2944, 3104, 3166, 3518, 3767, 4135, 4717, 4795, 4797, 4828, 5051, 5061, 5345, 5558, 5700, 5865, 5947, 6170, 6408, 6522, 6673, 6788, 7145, 7683, 8191, 8264, 8309, 8399, 8631, 8645, 8908, 10065, 10494, 10696, 10749, 10801, 10837, 10864, 11573, 11787, 11817, 11831, 11992, 12274, 12468, 12501, 12656, 12924, 13273, 13340, 13362, 13940, 14206, 14430, 14464, 14658, 14910, 14965, 15201, 15712, 15722, 16040, 16057, 16125, 16325, 16350, 16732, 17089, 17121, 17140, 17237, 17900, 17925, 17942, 18075, 18256, 18351, 19128, 19172, 19369, 19677, 19843, 20230, 20494, 20698, 20993, 21192, 21697, 21795, 22051, 22062, 23281, 23516, 23886, 24176, 24384, 24677, 25044, 25331, 25604, 25721, 25931, 25987, 26138, 26165, 26577, 26979, 27190, 27466, 28091, 28195, 29158, 29209, 29211, 29336, 29346, 29358, 29813, 29883, 29894, 29920, 29928, 30129, 30231, 30657, 30760, 31158, 31185, 31206, 31441, 31492, 31578, 31609, 31795, 31907, 32006, 32303, 32718, 32755, 32812, 32924, 33126, 33132, 33247, 33350, 33502, 33553, 34155, 34273, 34590, 34645, 34719, 35194, 35382, 35464, 35613, 35819, 35988, 36021, 36111, 36263, 36772, 36973, 37604, 37754, 37776, 38342, 38394, 38459, 38546, 38832, 38856, 39146, 39158, 39194, 39209, 39523, 39597, 39653, 39673, 39800, 39845, 39855, 39943, 40078, 40080, 40103, 40163, 40276, 40622, 40914, 41115, 41265, 41650, 41755, 42282, 42476, 42699, 42708, 42856, 42975, 43190, 43276, 43342, 43415, 43965, 44126, 44257, 44430, 44454, 44878, 45193, 45855, 45860, 45999, 46004, 46256, 46358, 46478, 46483, 46529, 46629, 46782, 46821, 46844, 47166, 47332, 47536, 47589, 48243, 48289, 48361, 48666, 49311, 49638, 49674, 49744, 50227, 50441, 50526, 50830, 50866, 50877, 50999, 51080, 51100, 51419, 51598, 53279, 53311, 53462, 53725, 54170, 54314, 54548, 54791, 54815, 54891, 54909, 56022, 56138, 56143, 56156, 56270, 56546, 56908, 56932, 56990, 57160, 57175, 57256, 57362, 58118, 58179, 58510, 58644, 58728, 59408, 59765, 59898, 59910, 60123, 60142, 60199, 60211, 60420, 60530, 60656, 60814, 60907, 60918, 61082, 61113, 61224, 61445, 61600, 61702, 61846, 61974, 62013, 62530, 62532, 62551, 62566, 63149, 63205, 63298, 63342, 63598, 63946, 64736, 64999, 65102, 65111, 65190, 65289, 65823, 66012, 66033, 66041, 66159, 66196, 66240, 66438, 66627, 66664, 66746, 66893, 66996, 67019, 67278, 67287, 67698, 68157, 68408, 68545, 68803, 68890, 68967, 68992, 69016, 69231, 69266, 69660, 70057, 70072, 70328, 70402, 70441, 70478, 70539, 70586, 70768, 70830, 70990, 71000, 71235, 71255, 71595, 71772, 71932, 72239, 72338, 72699, 72722, 72996, 73077, 73300, 73535, 73677, 74106, 74190, 74658, 74715, 74933, 74957, 74995, 75220, 75303, 75413, 75414, 76263, 76305, 76309, 77411, 77440, 77501, 78043, 78238, 78448, 79204, 79530, 79541, 79623, 79933, 79971, 80222, 80289, 80667, 80704, 80849, 81008, 81164, 81329, 81466, 81470, 81903, 81958, 81986, 82269, 82573, 82760, 82796, 82970, 83125, 83174, 83355, 83382, 83432, 84248, 84313, 84421, 84542, 84986, 85060, 85206, 85310, 85474, 85706, 85833, 86343, 86555, 86664, 86806, 87283, 87680, 87812, 87866, 88252, 88253, 88384, 88794, 89093, 89297, 89342, 90139, 90331, 90339, 90602, 90730, 90772, 90831, 90917, 91114, 91119, 91287, 91316, 92034, 92084, 92454, 92479, 92632, 92906, 92939, 93039, 93096, 93241, 93258, 93665, 93858, 94074, 94304, 94972, 95645, 95755, 95846, 95937, 96106, 96217, 96449, 96794, 96840, 96966, 96992, 97104, 97234, 97559, 97669, 97868, 97881, 98102, 98126, 98208, 98414, 98545, 98786, 99129, 99538, 99576, 99742, 99754, 99903]
--------------------------------------------------

0        10
1         8
2         9
3        10
4        10
         ..
99995     8
99996    10
99997     9
99998    10
99999    10
Name: stress_level, Length: 100000, dtype: int64

In [18]:
px.box(data_frame=df, x='stress_level')

In [21]:
df.drop(outlier_indices, axis= 0, inplace=True)
df

,age,gender,education_level,school_type,family_income,parent_education,urban_rural,previous_exam_score,previous_gpa,attendance_percentage,...,exam_difficulty,exam_preparation_days,questions_attempted,questions_correct,time_management_score,exam_anxiety_level,exam_score,performance_grade,pass_status,performance_level
0,20,Female,High School,Public,Middle,Unknown,Rural,78.36,2.95,81.49,...,Medium,27,95,86,78.398551,9.39,90.40,A,Pass,High
1,17,Male,High School,Public,Middle,Unknown,Suburban,73.40,2.89,84.75,...,Easy,4,100,86,87.170000,6.31,86.21,A,Pass,High
2,18,Other,Undergraduate,Public,Middle,Master,Urban,82.76,3.35,100.00,...,Easy,28,96,74,63.770000,9.87,76.11,B,Pass,Medium
3,20,Male,High School,Public,Middle,High School,Suburban,60.61,2.57,84.91,...,Medium,16,97,77,59.510000,9.68,79.74,B,Pass,Medium
4,16,Female,High School,Private,High,Bachelor,Suburban,74.79,2.84,88.21,...,Medium,28,98,52,84.640000,10.00,50.66,D,Pass,Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,17,Male,Undergraduate,Public,Upper-Middle,Unknown,Suburban,78.73,Unknown,89.67,...,Medium,5,95,62,76.130000,8.36,66.46,C,Pass,Medium
99996,14,Female,High School,Public,Upper-Middle,Bachelor,Suburban,75.70,2.98,83.87,...,Easy,24,94,91,84.290000,8.68,96.54,A,Pass,High
99997,16,Female,High School,Public,Upper-Middle,High School,Suburban,84.69,3.27,89.57,...,Medium,24,85,65,62.320000,9.97,74.66,C,Pass,Medium
99998,15,Female,High School,Private,High,Master,Rural,74.70,3.06,92.61,...,Medium,28,93,81,100.000000,10.00,85.85,A,Pass,High
99999,18,Female,Undergraduate,Charter,Lower-Middle,Unknown,Urban,76.73,2.97,90.32,...,Medium,1,92,52,78.398551,10.00,54.40,D,Pass,Low

In [22]:
cols = df.select_dtypes('str').columns.to_list()
cat_col_df = {}
for col in cols:
    cat_col_df[f'{col}'] = df.groupby(col)['exam_score'].median()

In [23]:
keys = cat_col_df.keys()

for key in keys:
    px.bar(data_frame= cat_col_df[key]).show()

In [24]:
num_cols = df.select_dtypes('number').columns.to_list()

In [25]:
num_cols

['age',
 'previous_exam_score',
 'attendance_percentage',
 'assignment_completion_rate',
 'study_hours_per_day',
 'self_study_hours',
 'online_learning_hours',
 'practice_tests_completed',
 'sleep_hours',
 'daily_screen_time',
 'physical_activity_hours',
 'stress_level',
 'online_course_hours',
 'exam_preparation_days',
 'questions_attempted',
 'questions_correct',
 'time_management_score',
 'exam_anxiety_level',
 'exam_score']

In [26]:
for x in ['online_learning_hours', 'daily_screen_time', 'physical_activity_hours', 'online_course_hours', 'questions_attempted',  'questions_correct', 'age']:

    num_cols.remove(x)

In [27]:
num_cols

['previous_exam_score',
 'attendance_percentage',
 'assignment_completion_rate',
 'study_hours_per_day',
 'self_study_hours',
 'practice_tests_completed',
 'sleep_hours',
 'stress_level',
 'exam_preparation_days',
 'time_management_score',
 'exam_anxiety_level',
 'exam_score']

In [28]:
df_corr = df[num_cols].corr(numeric_only = True).round(2)
df_corr_exam = df_corr.loc['exam_score',:]
df_corr_exam

previous_exam_score           0.49
attendance_percentage         0.16
assignment_completion_rate    0.22
study_hours_per_day           0.36
self_study_hours              0.34
practice_tests_completed      0.28
sleep_hours                   0.17
stress_level                 -0.12
exam_preparation_days         0.19
time_management_score         0.10
exam_anxiety_level           -0.13
exam_score                    1.00
Name: exam_score, dtype: float64

In [29]:
px.bar(data_frame= df_corr_exam,       labels= {'index' : 'Numerical Columns', 'value' : 'correlation with exam score'})

In [30]:
# Only run to help for Autocomplete
import streamlit as st
import pandas as pd
import plotly.express as px

In [31]:
df.to_csv(r'D:\CDSP\Sessions\Project\student_exam_performance_analysis\Student.csv')

In [32]:




%%writefile strm.py



import streamlit as st
import pandas as pd
import plotly.express as px

df = pd.read_csv(r'D:\CDSP\Sessions\Project\student_exam_performance_analysis\Student.csv')


cols = df.select_dtypes('str').columns.to_list()
cat_col_df = {}
for col in cols:
    cat_col_df[f'{col}'] = df.groupby(col)['exam_score'].median()

num_cols = df.select_dtypes('number').columns.to_list()

for x in ['online_learning_hours', 'daily_screen_time', 'physical_activity_hours', 'online_course_hours', 'questions_attempted',  'questions_correct', 'age', 'previous_exam_score']:

    num_cols.remove(x)

df_corr = df[num_cols].corr(numeric_only = True).round(2)
df_corr_exam = df_corr.loc['exam_score',:]








st.title('Student Exam Performance Analysis')


st.dataframe(df)

st.write('')

st.write('## The following charts show the effect of columns on the final exam score')


st.write('')


st.subheader('1. Catgorical Columns: Comparing Between each unique value in the Column and its average of final exam score.')

st.plotly_chart(px.bar(data_frame= cat_col_df['school_type']))

st.write('#### Private Schools has the highest average final exam score.')

st.plotly_chart(px.bar(data_frame= cat_col_df['family_income']))

st.write('#### There is a direct relationship between family income and average final exam score.')

st.plotly_chart(px.bar(data_frame= cat_col_df['break_frequency']))

st.write('#### Taking breaks Occasionally is the best choice for higher final exam score.')


st.plotly_chart(px.bar(data_frame= cat_col_df['internet_access']))

st.write('#### Students who have internet access have higher scores.')


st.write('')

st.write('')



st.subheader('2. Numerical Columns: Showing Correlation between Numerical Columns and final exam score.')


st.write('')
st.write('')




st.plotly_chart(px.bar(data_frame= df_corr_exam))


st.write('#### The highest 5 Correlations with exam score:')

st.write('##### 1. Study Hours Per Day')

st.write('##### 2. Self Study Hours')

st.write('##### 3. Practice Test Completed')

st.write('##### 4. Exam Preparation Days')

st.write('##### 5. Sleep hours')

st.write('')
st.write('')
st.write('')

st.write('#### The 2 Negative Correlations With Exam Score:')


st.write('##### 1. Stress Level')

st.write('##### 2. Anxiety Exam Level')

Overwriting strm.py